EmbeddedStock2/Models/Category.cs
using System.Collections.Generic;

namespace EmbeddedStock2.Models
{
    public class Category
    {
        public Category()
        {
            ComponentTypeCategory = new List<ComponentTypeCategory>();
        }

        public int CategoryId { get; set; }
        public string Name { get; set; }
        public ICollection<ComponentTypeCategory> ComponentTypeCategory { get; protected set; }
    }
}

EmbeddedStock2/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmbeddedStock2.Models;

namespace EmbeddedStock2.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly EmbeddedStock2Context _context;

        public CategoriesController(EmbeddedStock2Context context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {

            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.ComponentTypeCategory)
                .ThenInclude(ct => ct.ComponentType)
                .SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            ViewBag.ComponentTypes = _context.ComponentTypes.Select(c => new SelectListItem()
            {
                Text = c.ComponentName, Value = c.ComponentTypeId.ToString() 
                
            });

            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,Name")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.SingleOrDefaultAsync(m => m.CategoryId == id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

EmbeddedStock2/Controllers/ComponentTypesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmbeddedStock2.Models;
using EmbeddedStock2.ViewModels;
using FreeImageAPI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Internal;

namespace EmbeddedStock2.Controllers
{
    public class ComponentTypesController : Controller
    {
        private readonly EmbeddedStock2Context _context;

        public ComponentTypesController(EmbeddedStock2Context context)
        {
            _context = context;
        }

        // GET: ComponentTypes
        public async Task<IActionResult> Index(int categoryId)
        {
            ViewBag.Categories = _context.Categories
                .Select(c => new SelectListItem() { Text = c.Name, Value = c.CategoryId.ToString() })
                .ToList();
            var componentTypes = _context.ComponentTypes.AsQueryable();
            if (categoryId != 0)
            {
                componentTypes = componentTypes.Where(c => c.ComponentTypeCategory.Any(o => o.CategoryId == categoryId));
            }
            return View(await componentTypes.AsNoTracking().Include(ct => ct.Image).ToListAsync());
        }

        // GET: ComponentTypes/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var componentType = await _context.ComponentTypes
                .Include(ct => ct.Image)
                .SingleOrDefaultAsync(m => m.ComponentTypeId == id);


            if (componentType == null)
            {
                return NotFound();
            }

            return View(componentType);
        }

        // GET: ComponentTypes/Create
        public IActionResult Create()
        {
            var categories = _context.Categories
                .Select(c => new SelectListItem() { Text = c.Name, Value = c.CategoryId.ToString() })
                .ToList();
            if (categories.Count > 0)
            {
                ViewData["categories"] = categories;
                return View();
            }
            return View("NoCategories");
        }

        // POST: ComponentTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateComponentTypeViewModel componentTypeViewModel)
        {
            if (ModelState.IsValid)
            {
                //Make image
                byte[] image;
                byte[] thumbnail;
                using (var m = new MemoryStream())
                {
                    await componentTypeViewModel.ImageUpload.CopyToAsync(m);
                    image = m.ToArray();
                }
                //Make thumbnail
                using (var m = new MemoryStream())
                {
                    await componentTypeViewModel.ImageUpload.CopyToAsync(m);
                    using (var ti = new FreeImageBitmap(componentTypeViewModel.ImageUpload.OpenReadStream()))
                    {
                        var thumb = ti.GetThumbnailImage(100, true);
                        using (var nm = new MemoryStream())
                        {
                            thumb.Save(nm,Util.Util.FindImageFormat(componentTypeViewModel.ImageUpload.ContentType));
                            thumbnail = nm.ToArray();
                        }
                    }
                } 
                    var componentType = new ComponentType
                    {
                        ComponentName = componentTypeViewModel.ComponentName,
                        AdminComment = componentTypeViewModel.AdminComment,
                        ComponentInfo = componentTypeViewModel.ComponentInfo,
                        Datasheet = componentTypeViewModel.Datasheet,
                        Location = componentTypeViewModel.Location,
                        WikiLink = componentTypeViewModel.WikiLink,
                        Manufacturer = componentTypeViewModel.Manufacturer,
                        Image = new EsImage
                        {
                            ImageData = image,
                            Thumbnail = thumbnail,
                            ImageMimeType = componentTypeViewModel.ImageUpload.ContentType
                        }
                    };
                var category = await _context.Categories.FirstOrDefaultAsync(c => c.CategoryId == componentTypeViewModel.Category);
                if (category != null)
                {
                    _context.Add(componentType);
                    await _context.SaveChangesAsync();

                    _context.Add(new ComponentTypeCategory { Category = category, ComponentType = componentType });
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(componentTypeViewModel);
        }

        // GET: ComponentTypes/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var componentType = await _context.ComponentTypes.Include(c => c.Image).SingleOrDefaultAsync(m => m.ComponentTypeId == id);
            this.ViewData["categories"] = _context.Categories
                .Select(c => new SelectListItem() { Text = c.Name, Value = c.CategoryId.ToString() })
                .ToList();
            if (componentType == null)
            {
                return NotFound();
            }
            return View(componentType);
        }

        // POST: ComponentTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, ComponentType componentType, IFormFile imageFile)
        {

            if (id != componentType.ComponentTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (imageFile.Length > 0)
                    {
                        var stream = imageFile.OpenReadStream();
                        var bitmap = FreeImageBitmap.FromStream(stream);
                        var thumbnail = bitmap.GetThumbnailImage(1000, true);

                        using (var m = new MemoryStream())
                        {
                            bitmap.Save(m, format: bitmap.ImageFormat);
                            componentType.Image.ImageData = m.ToArray();
                            
                        }
                        using (var m = new MemoryStream())
                        {
                            thumbnail.Save(m, format: FREE_IMAGE_FORMAT.FIF_JPEG);
                            componentType.Image.Thumbnail = m.ToArray();
                        }
                    }

                    _context.Update(componentType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComponentTypeExists(componentType.ComponentTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(componentType);
        }

        // GET: ComponentTypes/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var componentType = await _context.ComponentTypes
                .SingleOrDefaultAsync(m => m.ComponentTypeId == id);
            if (componentType == null)
            {
                return NotFound();
            }

            return View(componentType);
        }

        // POST: ComponentTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var componentType = await _context.ComponentTypes.SingleOrDefaultAsync(m => m.ComponentTypeId == id);
            _context.ComponentTypes.Remove(componentType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComponentTypeExists(long id)
        {
            return _context.ComponentTypes.Any(e => e.ComponentTypeId == id);
        }
    }
}

EmbeddedStock2/Views/Categories/Create.cshtml
@model EmbeddedStock2.Models.Category

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EmbeddedStock2/Views/Categories/Delete.cshtml
@model EmbeddedStock2.Models.Category

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EmbeddedStock2/Views/Categories/Details.cshtml
@model EmbeddedStock2.Models.Category

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Component types in category
        </dt>
        <dd>
            @foreach (var ct in Model.ComponentTypeCategory)
            {
                <a href="@Url.Action("Details","ComponentTypes", new {id = ct.ComponentType.ComponentTypeId})">@ct.ComponentType.ComponentName</a>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CategoryId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EmbeddedStock2/Views/Categories/Edit.cshtml
@model EmbeddedStock2.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EmbeddedStock2/Views/Categories/Index.cshtml
@model IEnumerable<EmbeddedStock2.Models.Category>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CategoryId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CategoryId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CategoryId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>